### ISSUE TITLE
bg.png file is missing

### ISSUE THREAD

**Issue by BaseMax** [sharanya02/Text-file-to-handwritten-pdf-file#1]
Hello,

The `bg.png` file is missing, you can upload this into repository.
Good luck,

Regards,
Max Base

**Comment by projjal1** [comment]
It's not missing. It's in myfont folder.
The path for images is not set. 
The owner has moved the images to the folder after compiling the code.

Everywhere the code loads images add myfont directory to it.

**Comment by BaseMax** [comment]
Thanks for your message.

I see, I'm sending a PR.
I also found another problem in the source code.

Cheers,
Max Base

**Comment by projjal1** [comment]
There is a bug in the sense that the code does not stop execution and freezes at some point while converting to pdf files.

**Comment by projjal1** [comment]
Another one is with opening brackets called bracketcl.png.  In the source code it's misspelled.

**Comment by BaseMax** [comment]
I changed `braketclose` to `braketcl`.

Good luck,
Thanks

**Comment by sharanya02** [comment]
hello guys! can you check it out if its fine now or not?

**Comment by projjal1** [comment]
No its not working. You have included absolute path. Use relative path.  I myself am pretty noob in git. So can you communicate elsewhere. I can help you with the changes.

**Comment by projjal1** [comment]
In line no 2, 12 instead of using "c:/Users/shara/myfont/%s.png",  use "myfont/%s.png".
In line 63 in path use "myfont/bg.png".

Thats it.

**Comment by projjal1** [comment]
Even after making changes, I see that while the script is making the pdf file from imagelists, it is freezing.  Please give an update on this.

**Comment by sharanya02** [comment]
> Even after making changes, I see that while the script is making the pdf file from imagelists, it is freezing. Please give an update on this.

It's not exactly freezing but like its taking 5 to 10 minutes to convert from png to pdf. Any solution for this?

**Comment by projjal1** [comment]
I have found a fast solution. Doing a PR request. Look into the commit. The newly proposed one takes 5-6 secs.

**Comment by projjal1** [comment]
Now i hope issues are fixed. Someone just needs to work with the margins.
