### ISSUE TITLE
Incompleate requirements.txt

### ISSUE THREAD

**Issue by bmnidhin** [sharanya02/Text-file-to-handwritten-pdf-file#10]
requirements.txt is incomplete. Not all dependencies and versions are listed.

ie `$pip install requirements.txt `throws an error

 My PL may resolve this issue

**Comment by projjal1** [comment]
Use
pip install -r requirements.txt 

To install modules from file.

**Comment by sharanya02** [comment]
> requirements.txt is incomplete. Not all repositories and versions are listed.
> 
> ie `$pip install requirements.txt `throws an error
> 
> My PL may resolve this issue

I've merged your PR. Thank you!
